resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/devdays-2016/hello-spring-boot.git
    branch: master

jobs:
- name: compile-job
  plan:
  - {get: source-code, trigger: true}
  - task: compile
    config:
      inputs:
        - name: source-code
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      run:
        path: source-code/script/test
