resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/devdays-2016/hello-spring-boot.git
    branch: master

- name: cf-deploy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: devdays
    space: development

jobs:
- name: compile-job
  serial: true
  plan:
  - {get: source-code, trigger: true}
  - task: compile
    config:
      inputs:
        - name: source-code
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      run:
        path: source-code/script/test
  - task: binary
    config:
      inputs:
        - name: source-code
      outputs:
        - name: build-resource
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      run:
        path: source-code/script/binary
  - put: cf-deploy
    params:
      manifest: build-resource/manifest.yml
