resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/devdays-2016/hello-spring-boot.git
    branch: master

jobs:
- name: compile-job
  plan:
  - get: source-code
  - task: compile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      run:
        path: ls
        args: ["-lA"]
